const CMD_GENERATE = 'generate';
const CMD_CHECK = 'check';

const configUrl = new URL('../project-structure.json', import.meta.url);
const markerStart = '<!-- project-structure-gen:start -->';
const markerEnd = '<!-- project-structure-gen:end -->';

//<skill-gen>
// ---
// name: generated-repo-surfaces
// description: "Use when changing generated workflows, OpenAPI artifacts, project-structure blocks, or repo-local skills."
// paths:
//   - tools/project-structure-gen/**
//   - tools/openapi-gen/**
//   - tools/workflow-fragments/**
//   - .github/workflows/**
//   - required-workflows.json
//   - packages/api-core/openapi.json
// ---
//
// # Generated Repo Surfaces
//
// Do not hand-maintain generated artifacts when a generator exists. Edit the
// source fragment or config, then run the matching generate/check command.
//
// ## Commands
//
// - `bun run workflows:generate` / `bun run workflows:check`
// - `bun run structure:generate` / `bun run structure:check`
// - `bun run openapi:generate` / `bun run openapi:check`
// - `bun run skills:generate` / `bun run skills:check`
//
// `bun run check:generated` must stay green in CI.
//</skill-gen>

/** Project-structure generator configuration loaded from project-structure.json. */
interface StructureConfig {
  readonly targets: ReadonlyArray<string>;
  readonly sections: ReadonlyArray<{
    readonly path: string;
    readonly description: string;
  }>;
}

/** Directory tree node used while rendering the project structure block. */
interface TreeNode {
  readonly name: string;
  readonly children: Map<string, TreeNode>;
  description?: string;
}

/** Returns true when a value matches the project-structure generator config shape. */
const isStructureConfig = (value: unknown): value is StructureConfig => {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const targets = Reflect.get(value, 'targets');
  const sections = Reflect.get(value, 'sections');

  return (
    Array.isArray(targets) &&
    targets.every(
      (target) => typeof target === 'string' && target.length > 0
    ) &&
    Array.isArray(sections) &&
    sections.every((section) => {
      if (typeof section !== 'object' || section === null) {
        return false;
      }

      const path = Reflect.get(section, 'path');
      const description = Reflect.get(section, 'description');

      return (
        typeof path === 'string' &&
        path.length > 0 &&
        typeof description === 'string'
      );
    })
  );
};

/** Renders the marked project-structure block from configured sections. */
function renderBlock(config: StructureConfig): string {
  const lines = [
    markerStart,
    '<!-- AUTO-GENERATED by project-structure-gen -- DO NOT EDIT THIS BLOCK -->',
    '```text',
    '.',
    ...renderTreeLines(buildTree(config.sections), ''),
    '```',
    markerEnd
  ];

  return lines.join('\n');
}

/** Builds a directory tree from configured section paths and descriptions. */
function buildTree(config: StructureConfig['sections']): TreeNode {
  const root = createTreeNode('.');

  for (const section of config) {
    const parts = section.path.split('/').filter((part) => part.length > 0);
    let current = root;

    for (const part of parts) {
      const child = current.children.get(part) ?? createTreeNode(part);
      current.children.set(part, child);
      current = child;
    }

    current.description = section.description;
  }

  return root;
}

/** Creates an empty directory tree node with the given label. */
function createTreeNode(name: string): TreeNode {
  return {
    name,
    children: new Map()
  };
}

/** Renders ASCII tree lines for one node and its descendants. */
function renderTreeLines(
  node: TreeNode,
  prefix: string
): ReadonlyArray<string> {
  const lines: Array<string> = [];
  const children = [...node.children.values()];

  children.forEach((child, index) => {
    const isLast = index === children.length - 1;
    const connector = isLast ? '`-- ' : '|-- ';
    const childPrefix = isLast ? '    ' : '|   ';
    const label =
      child.description === undefined
        ? child.name
        : `${child.name} - ${child.description}`;

    lines.push(`${prefix}${connector}${label}`);
    lines.push(...renderTreeLines(child, `${prefix}${childPrefix}`));
  });

  return lines;
}

/** Replaces the marked project-structure block inside a target markdown file. */
function replaceMarkedBlock(
  target: string,
  content: string,
  options: { readonly block: string }
): string {
  const start = content.indexOf(markerStart);
  const end = content.indexOf(markerEnd);
  const duplicateStart =
    start === -1
      ? -1
      : content.indexOf(markerStart, start + markerStart.length);
  const duplicateEnd =
    end === -1 ? -1 : content.indexOf(markerEnd, end + markerEnd.length);

  if (
    start === -1 ||
    end === -1 ||
    end < start ||
    duplicateStart !== -1 ||
    duplicateEnd !== -1
  ) {
    throw new Error(
      `${target} must contain ${markerStart} and ${markerEnd} markers`
    );
  }

  const before = content.slice(0, start);
  const after = content.slice(end + markerEnd.length);

  return `${before}${options.block}${after}`;
}

const main = async (): Promise<void> => {
  const command = process.argv[2];

  if (command !== CMD_GENERATE && command !== CMD_CHECK) {
    console.error(
      `usage: bun run tools/project-structure-gen/src/index.ts <${CMD_GENERATE}|${CMD_CHECK}>`
    );
    process.exit(1);
  }

  const rawConfig: unknown = await Bun.file(configUrl).json();

  if (!isStructureConfig(rawConfig)) {
    console.error('project-structure-gen: invalid project-structure.json');
    process.exit(1);
  }

  const config = rawConfig;
  const renderedBlock = renderBlock(config);
  const outOfDate: Array<string> = [];

  const targetResults = await Promise.all(
    config.targets.map(async (target) => {
      const file = Bun.file(target);
      const current = await file.text();
      const next = replaceMarkedBlock(target, current, {
        block: renderedBlock
      });

      return { current, next, target };
    })
  );

  for (const { current, next, target } of targetResults) {
    if (current === next) {
      continue;
    }

    if (command === CMD_GENERATE) {
      await Bun.write(target, next);
      console.log(`generate: updated ${target}`);
    } else {
      outOfDate.push(target);
    }
  }

  if (command === CMD_CHECK) {
    if (outOfDate.length === 0) {
      console.log('check: all project structure blocks are up-to-date');
      process.exit(0);
    }

    console.error(
      `check: ${outOfDate.length} project structure block(s) are out of date`
    );
    for (const target of outOfDate) {
      console.error(`OUTDATED: ${target}`);
    }
    console.error('run: bun run structure:generate');
    process.exit(1);
  }
};

try {
  await main();
} catch (error) {
  console.error(
    'project-structure-gen failed:',
    error instanceof Error ? error.message : String(error)
  );
  process.exit(1);
}
