import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { stringify } from 'yaml';
import type { MergedWorkflow } from './merge';

const TAG_NAME = 'gen-github-workflow';
const DEFAULT_RUNNER = 'ubuntu-latest';

/** Build the auto-generated banner listing the source files for a workflow. */
function makeHeader(sources: string[]): string {
  const unique = [...new Set(sources)];
  const lines = [
    `# AUTO-GENERATED by ${TAG_NAME} -- DO NOT EDIT`,
    ...unique.map((s) => `# Source: ${s}`)
  ];
  return lines.join('\n');
}

const YML_SUFFIX_RE = /\.yml$/;
const GENERATED_PREFIX = '# AUTO-GENERATED by gen-github-workflow';

/**
 * Canonical key order for GitHub Actions workflows.
 * Keys not in this list are appended in their original order after the known keys.
 */
const KEY_ORDER = [
  'name',
  'on',
  'permissions',
  'concurrency',
  'env',
  'defaults',
  'jobs'
];

/**
 * Canonical trigger order for the `on` key.
 */
const TRIGGER_ORDER = [
  'push',
  'pull_request',
  'pull_request_target',
  'workflow_dispatch',
  'workflow_call',
  'schedule',
  'release',
  'issues',
  'issue_comment',
  'create',
  'delete',
  'deployment',
  'page_build',
  'repository_dispatch'
];

/** Narrow a value to a plain (non-array) object. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Sort object keys based on a priority list. Unknown keys go at the end in original order.
 */
function sortKeys(
  data: Record<string, unknown>,
  order: string[]
): Record<string, unknown> {
  const ordered: Record<string, unknown> = {};

  for (const key of order) {
    if (key in data) {
      ordered[key] = data[key];
    }
  }

  for (const key of Object.keys(data)) {
    if (!(key in ordered)) {
      ordered[key] = data[key];
    }
  }

  return ordered;
}

/**
 * Reorder object keys to match canonical GitHub Actions ordering.
 * Also sorts `on` triggers in canonical order.
 */
function reorderKeys(data: Record<string, unknown>): Record<string, unknown> {
  const ordered = sortKeys(data, KEY_ORDER);

  if (isRecord(ordered.on)) {
    ordered.on = sortKeys(ordered.on, TRIGGER_ORDER);
  }

  if (isRecord(ordered.jobs)) {
    const jobs = ordered.jobs;
    const sortedJobs: Record<string, unknown> = {};
    for (const key of Object.keys(jobs).sort()) {
      sortedJobs[key] = jobs[key];
    }
    ordered.jobs = sortedJobs;
  }

  return ordered;
}

const JOB_KEY_ORDER = [
  'name',
  'if',
  'needs',
  'runs-on',
  'permissions',
  'environment',
  'concurrency',
  'timeout-minutes',
  'strategy',
  'env',
  'defaults',
  'steps'
];

/**
 * Inject `runs-on: DEFAULT_RUNNER` into jobs that don't already specify
 * `runs-on` and don't use `uses:` (reusable workflow calls).
 */
function applyJobDefaults(
  data: Record<string, unknown>
): Record<string, unknown> {
  const jobs = data.jobs;
  if (!isRecord(jobs)) {
    return data;
  }

  const patched: Record<string, unknown> = {};
  for (const [jobId, jobConfig] of Object.entries(jobs)) {
    if (!isRecord(jobConfig) || 'uses' in jobConfig || 'runs-on' in jobConfig) {
      patched[jobId] = jobConfig;
      continue;
    }
    const withRunner = { ...jobConfig, 'runs-on': DEFAULT_RUNNER };
    patched[jobId] = sortKeys(withRunner, JOB_KEY_ORDER);
  }

  return { ...data, jobs: patched };
}

/**
 * Serialize a merged workflow to YAML with the gen-github-workflow header.
 */
function renderWorkflow(workflow: MergedWorkflow): string {
  const withDefaults = applyJobDefaults(workflow.data);
  const ordered = reorderKeys(withDefaults);
  const yamlBody = stringify(ordered, {
    lineWidth: 0,
    singleQuote: false
  });
  const header = makeHeader(workflow.sources);
  return `${header}\n\n${yamlBody}`;
}

/** Check whether an unknown error is a missing-file error. */
function isEnoent(err: unknown): boolean {
  return err instanceof Error && 'code' in err && err.code === 'ENOENT';
}

/** Throw if a target path exists but lacks the gen-github-workflow header. */
async function checkExistingFile(filePath: string): Promise<void> {
  try {
    const existing = await readFile(filePath, 'utf-8');
    if (!existing.startsWith(GENERATED_PREFIX)) {
      throw new Error(
        `Refusing to overwrite ${filePath}: file exists but was not generated by gen-github-workflow. ` +
          'Remove it manually or add the gen-github-workflow header.'
      );
    }
  } catch (err) {
    if (isEnoent(err)) {
      return;
    }
    throw err;
  }
}

/** Render and write one workflow file, refusing to clobber foreign files. */
async function writeSingleWorkflow(
  name: string,
  workflow: MergedWorkflow,
  outputDir: string,
  verbose: boolean
): Promise<void> {
  const fileName = `${name}.yml`;
  const filePath = join(outputDir, fileName);

  await checkExistingFile(filePath);

  const content = renderWorkflow(workflow);
  await writeFile(filePath, content, 'utf-8');

  if (verbose) {
    // biome-ignore lint/suspicious/noConsole: CLI diagnostic output
    console.log(`output: wrote ${fileName}`);
  }
}

/**
 * Write merged workflows to the output directory.
 * Aborts if a file exists that was NOT previously generated by this tool.
 *
 * @param workflows - Merged workflows keyed by name.
 * @param outputDir - Directory to write `<name>.yml` files into.
 * @param verbose - When true, log each file written.
 * @throws Error when a target file exists without the generated header.
 */
export async function writeWorkflows(
  workflows: Map<string, MergedWorkflow>,
  outputDir: string,
  verbose = false
): Promise<void> {
  await mkdir(outputDir, { recursive: true });

  await Promise.all(
    [...workflows.entries()].map(([name, workflow]) =>
      writeSingleWorkflow(name, workflow, outputDir, verbose)
    )
  );
}

/**
 * Validate that required workflows are safe to use as branch protection checks.
 * A required workflow must run on every PR, so it must have a `pull_request`
 * trigger without `paths` or `paths-ignore` filters.
 *
 * @param workflows - Merged workflows keyed by name.
 * @throws Error listing every required workflow that would not run on all PRs.
 */
export function validateRequired(workflows: Map<string, MergedWorkflow>): void {
  const errors: string[] = [];

  for (const [name, workflow] of workflows) {
    if (!workflow.required) {
      continue;
    }

    const on = workflow.data.on;
    if (!isRecord(on)) {
      errors.push(
        `required workflow '${name}' has no triggers (sources: ${workflow.sources.join(', ')})`
      );
      continue;
    }

    const hasPullRequest = 'pull_request' in on || 'pull_request_target' in on;
    if (!hasPullRequest) {
      errors.push(
        `required workflow '${name}' has no pull_request trigger — it won't run on PRs and will block merges (sources: ${workflow.sources.join(', ')})`
      );
      continue;
    }

    const prTrigger = on.pull_request ?? on.pull_request_target;
    if (
      isRecord(prTrigger) &&
      ('paths' in prTrigger || 'paths-ignore' in prTrigger)
    ) {
      errors.push(
        `required workflow '${name}' has paths filters on its pull_request trigger — it won't run on all PRs and will block merges (sources: ${workflow.sources.join(', ')})`
      );
    }
  }

  if (errors.length > 0) {
    throw new Error(
      `Required workflow validation failed:\n${errors.map((e) => `  - ${e}`).join('\n')}`
    );
  }
}

/**
 * Collect job display names from workflows marked as required.
 * These are the GitHub Actions status check names used for branch protection.
 *
 * @param workflows - Merged workflows keyed by name.
 * @returns Sorted status-check names across all required workflows.
 */
export function collectRequired(
  workflows: Map<string, MergedWorkflow>
): string[] {
  const checks: string[] = [];
  for (const [, workflow] of workflows) {
    if (!workflow.required) {
      continue;
    }
    const jobs = workflow.data.jobs;
    if (!isRecord(jobs)) {
      continue;
    }
    for (const [jobKey, jobConfig] of Object.entries(jobs)) {
      if (isRecord(jobConfig) && typeof jobConfig.name === 'string') {
        checks.push(jobConfig.name);
      } else {
        checks.push(jobKey);
      }
    }
  }
  return checks.sort();
}

const JSON_LINE_WIDTH = 120;

/** Serialize a string array as JSON, single-line when it fits the width budget. */
function formatJson(data: string[]): string {
  const items = data.map((s) => JSON.stringify(s)).join(', ');
  const compact = `[${items}]`;
  if (compact.length <= JSON_LINE_WIDTH) {
    return `${compact}\n`;
  }
  return `${JSON.stringify(data, null, 2)}\n`;
}

/**
 * Write the required-workflows.json file in the base folder.
 *
 * @param requiredChecks - Status-check names to persist.
 * @param baseDir - Folder that holds required-workflows.json.
 * @param verbose - When true, log the write.
 */
export async function writeRequiredWorkflows(
  requiredChecks: string[],
  baseDir: string,
  verbose = false
): Promise<void> {
  const filePath = join(baseDir, 'required-workflows.json');
  const content = formatJson(requiredChecks);
  await writeFile(filePath, content, 'utf-8');
  if (verbose) {
    // biome-ignore lint/suspicious/noConsole: CLI diagnostic output
    console.log(
      `output: wrote required-workflows.json (${requiredChecks.length} check(s))`
    );
  }
}

/**
 * Check if required-workflows.json is up-to-date.
 *
 * @param requiredChecks - Status-check names the file should contain.
 * @param baseDir - Folder that holds required-workflows.json.
 * @returns A diff when the file is missing or differs, otherwise undefined.
 */
export async function checkRequiredWorkflows(
  requiredChecks: string[],
  baseDir: string
): Promise<FileDiff | undefined> {
  const filePath = join(baseDir, 'required-workflows.json');
  const expected = formatJson(requiredChecks);

  let actual: string;
  try {
    actual = await readFile(filePath, 'utf-8');
  } catch {
    return { file: 'required-workflows.json', type: 'missing', expected };
  }

  // Normalize JSON before comparing (biome may reformat based on line width)
  const normalizeJson = (s: string) => {
    try {
      return JSON.stringify(JSON.parse(s));
    } catch {
      return s;
    }
  };

  if (normalizeJson(actual) !== normalizeJson(expected)) {
    return {
      file: 'required-workflows.json',
      type: 'changed',
      expected,
      actual
    };
  }
  return;
}

export interface FileDiff {
  file: string;
  type: 'missing' | 'changed' | 'stale';
  expected?: string;
  actual?: string;
}

/** Diff one rendered workflow against the file on disk, or undefined if equal. */
async function checkSingleWorkflow(
  name: string,
  workflow: MergedWorkflow,
  outputDir: string
): Promise<FileDiff | undefined> {
  const fileName = `${name}.yml`;
  const filePath = join(outputDir, fileName);
  const expected = renderWorkflow(workflow);

  let actual: string;
  try {
    actual = await readFile(filePath, 'utf-8');
  } catch {
    return { file: fileName, type: 'missing', expected };
  }

  if (actual !== expected) {
    return { file: fileName, type: 'changed', expected, actual };
  }
  return;
}

/** Find generated workflow files that no longer have any source fragment. */
async function findStaleFiles(
  outputDir: string,
  workflows: Map<string, MergedWorkflow>
): Promise<FileDiff[]> {
  const diffs: FileDiff[] = [];
  let existingFiles: string[];
  try {
    existingFiles = await readdir(outputDir);
  } catch {
    return [];
  }

  const checkResults = await Promise.all(
    existingFiles
      .filter((file) => file.endsWith('.yml'))
      .map(async (file) => {
        const filePath = join(outputDir, file);
        try {
          const content = await readFile(filePath, 'utf-8');
          if (!content.startsWith(GENERATED_PREFIX)) {
            return;
          }
        } catch {
          return;
        }

        const workflowName = file.replace(YML_SUFFIX_RE, '');
        if (!workflows.has(workflowName)) {
          return { file, type: 'stale' } satisfies FileDiff;
        }
        return;
      })
  );

  for (const result of checkResults) {
    if (result) {
      diffs.push(result);
    }
  }

  return diffs;
}

/**
 * Check mode: generate workflows in memory and compare against existing files.
 * Returns a list of diffs. Empty list means everything is up-to-date.
 *
 * @param workflows - Merged workflows keyed by name.
 * @param outputDir - Directory holding the existing `<name>.yml` files.
 * @returns Missing, changed, and stale diffs; empty when everything matches.
 */
export async function checkWorkflows(
  workflows: Map<string, MergedWorkflow>,
  outputDir: string
): Promise<FileDiff[]> {
  const workflowResults = await Promise.all(
    [...workflows.entries()].map(([name, workflow]) =>
      checkSingleWorkflow(name, workflow, outputDir)
    )
  );

  const diffs: FileDiff[] = workflowResults.filter(
    (d): d is FileDiff => d !== undefined
  );

  const stale = await findStaleFiles(outputDir, workflows);
  diffs.push(...stale);

  return diffs;
}

/** Format a missing-file diff as a single line. */
function formatMissing(diff: FileDiff): string {
  return `MISSING: ${diff.file} (would be created by generate)`;
}

/** Format a changed-file diff as a line-by-line patch block. */
function formatChanged(diff: FileDiff): string {
  const lines = [`CHANGED: ${diff.file}`];
  const expectedLines = diff.expected?.split('\n') ?? [];
  const actualLines = diff.actual?.split('\n') ?? [];
  const maxLen = Math.max(expectedLines.length, actualLines.length);
  for (let i = 0; i < maxLen; i++) {
    const exp = expectedLines[i] ?? '';
    const act = actualLines[i] ?? '';
    if (exp !== act) {
      if (act) {
        lines.push(`  - ${act}`);
      }
      if (exp) {
        lines.push(`  + ${exp}`);
      }
    }
  }
  return lines.join('\n');
}

/** Format a stale-file diff as a single line. */
function formatStale(diff: FileDiff): string {
  return `STALE: ${diff.file} (no longer has source fragments, should be removed)`;
}

/**
 * Format diffs for human-readable output.
 *
 * @param diffs - Diffs to render.
 * @returns Newline-joined description, one block per diff.
 */
export function formatDiffs(diffs: FileDiff[]): string {
  return diffs
    .map((diff) => {
      switch (diff.type) {
        case 'missing':
          return formatMissing(diff);
        case 'changed':
          return formatChanged(diff);
        case 'stale':
          return formatStale(diff);
        default:
          return `UNKNOWN: ${diff.file}`;
      }
    })
    .join('\n');
}
